export const kurdishStrings = {
  appName: 'لیمۆ',
  landingSubtitle: 'تەنها بۆ هەولێر و سلێمانی و دهۆک',
  signInWithGoogle: 'بە گووگڵ بچۆ ژوورەوە',
  termsAcceptance: 'بە چوونەژوورەوە، ڕێکار و مەرجەکانمان قبوڵ دەکەیت',

  navRides: 'گەشتەکان',
  navAccount: 'هەژمار',
  back: 'گەڕانەوە',

  erbil: 'هەولێر',
  suli: 'سلێمانی',
  duhok: 'دهۆک',

  signIn: 'چوونە ژوورەوە',
  signUp: 'تۆمارکردن',
  signOut: 'دەرچوون',
  welcomeBack: 'بەخێربێیتەوە',
  noAccount: 'هەژمارت نییە؟',
  continueWithGoogle: 'بە گووگڵ بەژداربە',
  or: 'یانیش',
  email: 'ئیمێل',
  phone: 'تەلەفۆن',
  password: 'ژمارەی نهێنی',
  fullName: 'ناوی تەواو',
  optional: 'ئارەزووی',
  continue: 'بڕۆ',

  iAm: 'من خۆم..',
  chooseRole: 'تۆ خۆت چی؟',
  passenger: 'سەرنشینم',
  passengerDesc: 'دەمەوێ ئۆتۆمبێلێکم دەسکەوێ',
  driver: 'شۆفێڕ',
  driverDesc: 'ئۆتۆمبێلم هەیە و سەرنشینم ئەوێ',
  both: 'هەردووکی',
  bothDesc: 'هەردووکی ئەکەم',
  createAccount: 'تۆمار',
  enterDetails: 'زانیارییەکانت تۆمارکە',

  verifyIdentity: 'خۆت بناسێنە',
  verifyDesc: 'ناسنامەکەت بنێرە تا دڵنیا بین کە خۆتی. کاتێکی کەمی پێ دەچێ.',
  uploadId: 'ناسنامەکەت بنێرە',
  uploadIdDesc: 'کارتی نیشتیمانی',
  takeSelfie: 'سێڵفییەک بگرە',
  takeSelfieDesc: 'ئێستا وێنەیەک بگرە',
  submitVerification: 'بینێرە',
  verificationApproved: 'تەسدیق کرا ✓',
  verificationPending: 'چاوەڕوانی تەسدیق',

  carDetails: 'زانیاری ئۆتۆمبێل',
  carMake: 'جۆری ئۆتۆمبێل',
  carModel: 'مۆدێلی ئۆتۆمبێل',
  carColor: 'ڕەنگی ئۆتۆمبێل',
  plateNumber: 'ژمارەی ئۆتۆمۆبیل',
  uploadLicense: 'مۆڵەتی شۆفێری',

  findRide: 'بگەڕێ',
  findRidePlaceholder: 'بگەڕێ...',
  fromWhere: 'لە کوێ؟',
  toWhere: 'بۆ کوێ؟',
  from: 'لە',
  to: 'بۆ',
  allCities: 'گشت شارەکان',
  noRidesFound: 'هیچ گەشتێک نەدۆزرایەوە',
  seatsLeft: 'شوێن ماوە',

  rideDetails: 'کورتەی گەشت',
  driverInfo: 'زانیاری شۆفێر',
  verified: 'ناسراوە ✓',
  price: 'نرخ',
  coffeeAndConvo: 'قاوەیەک بۆ شۆفێر، قسەی خۆش بۆ ڕێگا',
  coffeeNote: 'ئەمە بێ بەرامبەر نییە. پێویستە قاوەیەک بۆ شۆفێر بکڕی، لەوەشە شۆفێر داوای پارە بکا (کەمتر لە ٥ هەزار دینار)',
  seatsAvailable: 'شوێنی بەردەست',
  notes: 'تێبینی',
  requestRide: 'داوای گەشت بکە',
  requestSent: 'داواکاری گەشت نێردرا',
  contactRevealNote: 'ژمارەی پەیوەندی دوای دەسکەوتنی گەشت دەردەکەوێ',
  whereExactly: 'بۆ کام بەشی شار ئەچی؟',
  whereExactlyPlaceholder: 'کۆڵان، یاخود شوێنێکی تایبەت',
  sendRequest: 'بینێرە',
  cancel: 'پاشگەز',

  postRideTitle: 'گەشت پۆستکە',
  route: 'ئاڕاستە',
  selectCity: 'شارێک هەڵبژێرە',
  dateAndTime: 'بەروار و کات',
  date: 'بەروار',
  time: 'کات',
  availableSeats: 'شوێنی بەردەست',
  iqdAmount: 'دینار',
  iqdMax: 'نابێ زیاتر بێ لە ٥ هەزار دینار',
  communitySpirit: 'لە ڕای خوا',
  notesPlaceholder: 'هیچ تێبینییەکت هەیە بۆ سەرنشینەکە؟',
  postRideBtn: 'بڕۆ',
  ridePosted: 'گەشتەکەت پۆستکرا ✓',
  waitingRequests: 'چاوەڕوانی داواکاری سەرنشینەکان',
  postAnother: 'گەشتی دیکە پۆستکە',

  myRidesTitle: 'گەشتەکانم',
  noRequestedRides: 'هێشتا داوای هیچ گەشتێکت نەکردووە',
  myRidesAsDriver: 'گەشتەکانم (وەک شۆفێر)',
  upcoming: 'تازە گەشت',
  requests: 'داواکاری',
  contactInfo: 'زانیاری پەیوەندی',
  approve: 'پەسەندکردن',
  decline: 'ڕەتکردنەوە',
  approved: 'پەسەند کرا ✓',
  declined: 'ڕەت کرایەوە',
  passengerNote: 'تێبینی سەرنشین',

  profileTitle: 'خۆت',
  activateDriver: 'ببە بە شوفێر',
  activateDriverDesc: 'زانیاری ئۆتۆمبێل و مۆڵەتی شۆفێری دانێ',

  appShortName: 'ڕێ',
  newRide: 'گەشتێکی نوێ',
  seat: 'جێگا',
  aCoffee: 'قاوەیەک',
  money: 'پارە',
  make: 'جۆر',
  model: 'مۆدێل',
  color: 'ڕەنگ',
  rideNotesPlaceholder: 'هەر شتێک دەربارەی گەشتەکەت...',
  update: 'نوێکردنەوە',
  sendExclaim: 'بینێرە!',
  noPostedRides: 'هێشتا گەشتت پۆست نەکردووە',
  edit: 'دەسکاری',
  rideDetailsChanged: 'وردەکاری گەشتەکە گۆڕدرا',

  statusActive: 'چالاک',
  statusFull: '٠ جێ',
  statusCompleted: 'تەواو بوو',
  statusCancelled: 'هەڵوەشێنرایەوە',

  verifyDriverPrefix: 'بۆ بوون بە ',
  verifyDriverHighlight: 'شۆفێر',
  verifyDriverSuffix: '، پێویستە خۆت ڤێریفای بکەی',
  verifyDriverDesc: 'مۆڵەتی شۆفێری و سێلفی بنێرە بۆ ئەوەی ببی بە شۆفێڕ',
  kurdistan: 'کوردستان',
  licenseSent: 'ناردنمان! چاوەڕێی وەڵامبە',
  uploadLicensePhoto: 'وێنەی مۆڵەتنامەکەت ئەپلۆد بکە',
  selfieSuccess: 'سێلفییەکەت سەرکەوتوو بوو',
  takeSelfieShort: 'سێلفی بگرە',
  selfieDesc: 'وێنەیەکی ڕوونی ڕووخسارت',
  docsSent: 'ناسنامەکانت نێردران',
  verifiedCanPost: 'کاتێک پشتڕاست کرایتەوە، دەتوانیت گەشت پۆست بکەیت',
  backToHome: 'گەڕانەوە بۆ سەرەکی',
  pleaseWait: '...چاوەڕوان بە',
  send: 'بنێرە',

  driverLabel: 'شۆفێر',
  passengers: 'سەرنشینەکان',
  passengerFallback: 'سەرنشین',
  trip: 'گەشت',
  smoking: 'جگەرە',
  car: 'ئۆتۆ',
  seatsAvailableCount: 'جێگای بەردەست',
  statusCompletedBadge: 'تەواو بوو ✓',
  rideNotFound: 'ئەم گەشتە نەدۆزرایەوە',
  rideCompleted: 'گەشتەکە تەواو بوو',
  completedDate: 'ڕێکەوت:',
  manage: 'بەڕێوەبردن',
  cancelRide: 'هەڵوەشاندنەوە',
  withdraw: 'پاشگەزبوونەوە',
  noSeatsAvailable: 'جێ بەردەست نییە',
  yesSendIt: 'بەڵێ، بینێرە!',
  requestAccepted: 'قبوڵ کرا!',
  messageDriver: 'پەیامێک بنێرە بۆ شۆفێر',
  driverNoPhone: 'شۆفێر ژمارەی مۆبایلی زیاد نەکردووە',
  requestDeclined: 'داواکاریەکت ڕەت کرایەوە',
  driverDeclinedNote: 'شۆفێر داواکاریەکەتی قبوڵ نەکرد',
  requestSentDetail: 'داواکاریەکت نێردرا',
  approvedContactNote: 'کە داواکرییەکەت قبوڵ کرا، ژمارە مۆبایلی شۆفێر لێرە دەردەکەوێ',
  iWantIt: 'دەمەوێ!',
  pickup: 'سواربوون',
  pickupPlaceholder: 'لە کوێ سوار دەبی؟',
  dropoff: 'دابەزین',
  dropoffPlaceholder: 'لە کوێ دادەبەزی؟',
  phoneShareNote: 'دوای ئەوەی داواکارییەکت پەسەند کرا، ژمارەی مۆبایلەکەت لەگەڵ شۆفێر شێر دەکرێ',
  rateRideQuestion: 'گەشتەکە چۆن بوو بە لاتەوە؟',
  ratingDelayNote: 'هەڵسەنگاندنەکەت دوای ٧٢ کاتژمێر دەردەکەوێ',
  submitRating: 'ناردن',
  thanksForRating: 'سوپاس بۆ هەڵسەنگاندنەکەت!',
  confirmCancelRide: 'دڵنیایت لە هەڵوەشاندنەوەی ئەم گەشتە؟',
  confirmWithdraw: 'دڵنیایت لە پاشگەزبوونەوە؟',

  errorGeneric: 'هەڵەیەک ڕوویدا، دووبارە هەوڵبدەرەوە',
  errorReLogin: 'تکایە دووبارە بچۆرەوە ژوورەوە',
  errorSeatRestore: 'هەڵەیەک ڕوویدا لە گەڕاندنەوەی جێگا',
  errorSignInFirst: 'تکایە سەرەتا چوونەژوورەوە بکە',
  errorUploadBoth: 'تکایە مۆڵەتنامە و سێلفی بنێرە',
  errorSelectFromCity: 'تکایە شاری دەستپێکردن دیاری بکە',
  errorSelectToCity: 'تکایە شاری مەبەست دیاری بکە',
  errorSelectDate: 'تکایە بەرواری گەشت دیاری بکە',
  errorSelectTime: 'تکایە کاتی گەشت دیاری بکە',
  errorSelectCarMake: 'تکایە جۆری ئۆتۆمبێل دیاری بکە',
  errorSelectCarModel: 'تکایە مۆدێلی ئۆتۆمبێل دیاری بکە',
  errorSelectCarColor: 'تکایە ڕەنگی ئۆتۆمبێل دیاری بکە',
  errorSameCities: 'شوێنی چوون و هاتن ناتوانن هاوشێوە بن',
  errorNoSeats: 'جێگا بەردەست نییە',
  errorOccurred: 'هەڵەیەک ڕوویدا',

  notificationsTitle: 'ئاگاداری',
  newLabel: 'نوێ',
  previousLabel: 'پێشوو',
  noNotifications: 'هیچ ئاگادارییەک نییە',
  notifRequestReceived: 'دەیەوێ بێ',
  notifRequestApproved: 'قبوڵ کرا',
  notifPassengerCancelled: 'پاشگەزبووەوە',
  notifRideCompleted: 'هەڵیسەنگێنە',
  notifRideUpdated: 'گۆڕانکاری',

  profilePageTitle: 'پرۆفایل',
  infoSection: 'زانیاری',
  name: 'ناو',
  nameChangeNote: 'تەنها یەک جار دەتوانی ناوەکەت بگۆڕی',
  save: 'پاشەکەوتکردن',
  mobileNumber: 'ژمارەی مۆبایل',
  notAdded: 'زیاد نەکراوە',
  emailLabel: 'ئیمەیل',
  emailVerificationNote: 'لینکی پشتڕاستکردن دەنێردرێت بۆ ئیمەیلە نوێیەکە',
  roleSection: 'ڕۆڵ',
  accountType: 'جۆری هەژمار',
  statusLabel: 'بارودۆخ',
  verifiedStatus: 'پشتڕاستکراوە',
  unverifiedStatus: 'پشتڕاستنەکراوە',
  dangerSection: 'مەترسی',
  deleteAccount: 'هەژمارەکەت بسڕەوە',
  confirmDeleteAccount: 'دڵنیایت دەتەوێ هەژمارەکەت بسڕیتەوە؟',
  yesImSure: 'بەڵێ دڵنیام',
  driverAndPassenger: 'شۆفێر و سەرنشین',
  nameChanged: 'ناو گۆڕدرا',
  phoneChanged: 'ژمارە گۆڕدرا',
  errorPrefix: 'هەڵە: ',
  verificationLinkSent: 'لینکی پشتڕاستکردن نێردرا',
  errorNameChangeLimit: 'هێشتا ناتوانیت ناوەکەت بگۆڕیت',

}